export const data = {
  events: [
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "Austin,Tx",
      date_posted: "1 day ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Breaking Bread Building Bonds",
      desc: "Breaking Bread, Building Bonds is determined to organize one thousand meals and conversation across the city",
      img: "./src/assets/images/breaking_bread.jpg",
      location: "Chicago,Il",
      date_posted: "1 day ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Farmers Market",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/farmersmarket.jpg",
      location: "Montgomery,Al",
      date_posted: "2 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Science fair",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/sciencefair.jpg",
      location: "Akron,OH",
      date_posted: "3 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Technology Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/tech.png",
      location: "Albuquerque,NM",
      date_posted: "3 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "Denver,CO",
      date_posted: "3 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "Hartford,CT",
      date_posted: "2 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "Tallahassee,FL",
      date_posted: "3 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "Frankfort, KY",
      date_posted: "4 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "Boston,MA",
      date_posted: "5 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "St. Paul,MN",
      date_posted: "6 days ago",
      end: "Saturday 5 pm",
    },
    {
      title: "Community Clean up Day",
      desc: "Sint ad et quis pariatur reprehenderit nostrud enim exercitation aute ullamco commodo et.",
      img: "./src/assets/images/cleanup.jpg",
      location: "San Antoni,Tx",
      date_posted: "4 days ago",
      end: "Saturday 5 pm",
    },
  ],
};

export default data;
